# Generated by Django 3.0.2 on 2020-02-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='工号')),
                ('username', models.CharField(max_length=256, verbose_name='姓名')),
                ('department', models.CharField(max_length=64, unique=True, verbose_name='部门')),
            ],
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.TextField(blank=True, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='signature',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.ContractUser', verbose_name='签字人'),
            preserve_default=False,
        ),
    ]
