# Generated by Django 3.0.2 on 2020-02-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200213_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.ContractUser', verbose_name='签字人'),
        ),
    ]
