# Generated by Django 3.0.2 on 2020-02-13 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200213_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='签名时间'),
            preserve_default=False,
        ),
    ]
