# Generated by Django 3.0.2 on 2020-02-13 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contractuser_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='签名时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
