# Generated by Django 3.0.2 on 2020-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20200213_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractuser',
            name='department',
            field=models.CharField(max_length=64, null=True, verbose_name='部门'),
        ),
    ]
