# Generated by Django 3.0.2 on 2020-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20200213_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractuser',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
